const vehiclesData = {
  ebull: {
    id: "ebull",
    name: "eBull",
    type: "Electric cargo 3-wheeler",
    heroImage: "assets/images/ebull.png",
    badges: ["COMMERCIAL 3-WHEELER", "CARGO"],
    headline: "The Efficient Choice for Last-Mile Cargo.",
    specs: {
      "Top speed": "25 km/h",
      "Range": "50–110 km/charge",
      "Charging time": "8 hrs",
      "Motor type": "BLDC/PMSM",
      "Motor power": "1500W–2500W",
      "Battery": "LFP",
      "Operating voltage": "60V/72V",
      "Payload": "500 kg / 750 kg",
      "Braking": "Mechanical/Hydraulic",
      "Dimensions (mm)": "2750 × 1000 × 1770",
      "Tyre size": "3.75-12 / 4.00-12 in",
      "Ground clearance": "160 mm",
      "Speedometer": "Digital",
      "Motor warranty": "12 months",
      "Battery warranty": "36 months",
      "RTO registration": "Applicable",
      "ICAT / ARAI approved": "Yes"
    },
    heroSpecs: ["Range", "Payload", "Charging time", "Top speed"],
    colours: null
  },
  sardar: {
    id: "sardar",
    name: "Sardar",
    type: "Electric auto (commercial)",
    heroImage: "assets/images/sardar.jpg",
    badges: ["COMMERCIAL 3-WHEELER", "PASSENGER"],
    headline: "Urban Passenger Transit Redefined.",
    specs: {
      "Top speed": "60 km/h",
      "Range": "90–100 km/charge",
      "Charging time": "4 hrs",
      "Motor type": "BLDC hub motor",
      "Battery": "Li-ion 2.3 kW",
      "Operating voltage": "60V",
      "Key features": "Anti-theft, keyless entry",
      "Colours": "Black, Blue, Grey, Peach, Red"
    },
    heroSpecs: ["Range", "Top speed", "Charging time", "Battery"],
    colours: ["Black", "Blue", "Grey", "Peach", "Red"]
  },
  spike: {
    id: "spike",
    name: "Spike",
    type: "Electric scooter",
    heroImage: "assets/images/spike.png",
    badges: ["ELECTRIC 2-WHEELER", "COMMUTE"],
    headline: "Smart and Agile Daily Commuter.",
    specs: {
      "Top speed": "25 km/h",
      "Range": "70–80 km/charge",
      "Charging time": "4 hrs",
      "Motor type": "BLDC",
      "Motor power": "250W",
      "Battery": "Lithium",
      "Operating voltage": "60V",
      "Payload": "150 kg",
      "Braking": "F-Disc / R-Drum",
      "Dimensions (mm)": "1800 × 700 × 1100",
      "Tyre size": "90/100-10 in tubeless",
      "Ground clearance": "160 mm",
      "Speedometer": "Digital",
      "Key features": "Anti-theft, keyless entry",
      "Motor warranty": "12 months",
      "Battery warranty": "36 months",
      "RTO registration": "Not applicable",
      "ICAT / ARAI approved": "Yes",
      "Colours": "Red, Blue, White"
    },
    heroSpecs: ["Range", "Top speed", "Charging time", "Payload"],
    colours: ["Red", "Blue", "White"]
  },
  rs90: {
    id: "rs90",
    name: "RS90",
    type: "Electric scooter",
    heroImage: "assets/images/rs90.png",
    badges: ["ELECTRIC 2-WHEELER", "RELIABLE"],
    headline: "Reliable Performance for Every Journey.",
    specs: {
      "Top speed": "25 km/h",
      "Range": "50–90 km/charge",
      "Charging time": "4 hrs",
      "Motor type": "BLDC",
      "Motor power": "250W",
      "Battery": "LFP",
      "Operating voltage": "60V/72V",
      "Payload": "Rider + 150 kg",
      "Braking": "F-Drum / R-Disc",
      "Dimensions (mm)": "1800 × 690 × 1050",
      "Tyre size": "90/90-12 in tubeless",
      "Ground clearance": "160 mm",
      "Speedometer": "Digital",
      "Key features": "Anti-theft, keyless entry",
      "Motor warranty": "12 months",
      "Battery warranty": "36 months",
      "RTO registration": "Not applicable",
      "ICAT / ARAI approved": "Yes",
      "Colours": "Blue, Dark Blue, Grey, Red"
    },
    heroSpecs: ["Range", "Top speed", "Charging time", "Payload"],
    colours: ["Blue", "Dark Blue", "Grey", "Red"]
  },
  rs180: {
    id: "rs180",
    name: "RS180",
    type: "Electric scooter",
    heroImage: "assets/images/rs180.png",
    badges: ["ELECTRIC 2-WHEELER", "HIGH CAPACITY"],
    headline: "Maximum Capacity for Demanding Riders.",
    specs: {
      "Top speed": "25 km/h",
      "Range": "50–90 km/charge",
      "Charging time": "4 hrs",
      "Motor type": "BLDC",
      "Motor power": "250W",
      "Battery": "LFP",
      "Operating voltage": "60V/72V",
      "Payload": "Rider + 180 kg",
      "Braking": "F-Drum / R-Disc",
      "Dimensions (mm)": "1940 × 690 × 1050",
      "Tyre size": "90/100-10 in tubeless",
      "Ground clearance": "160 mm",
      "Speedometer": "Digital",
      "Key features": "Anti-theft, keyless entry",
      "Motor warranty": "12 months",
      "Battery warranty": "36 months",
      "RTO registration": "Not applicable",
      "ICAT / ARAI approved": "Yes",
      "Colours": "Black, Grey, Yellow"
    },
    heroSpecs: ["Range", "Top speed", "Charging time", "Payload"],
    colours: ["Black", "Grey", "Yellow"]
  }
};
